name: deploy
on: push
jobs: 
  test:
    name: testing if docker exists
    runs-on: ubuntu-20.04
    steps: 
      - name: check docker version
        run:  docker --version
      - name: checkout repo
        uses: actions/checkout@v2
      - name: pulling my repo
        run:  docker pull fuadnafiz98/bps:0.2
      - name: generating output
        run:  docker run -v "$(pwd)":/app fuadnafiz98/bps:0.2
      - name: check output
        run:  ls -lah out
        



# name: deploy

# on: push

# jobs: 
#   test:
#     name: test job
#     runs-on: ubuntu-20.04
#     steps:
#       - name: step-00
#         uses: actions/checkout@v2
#       - name: step-01
#         run : sudo apt update && sudo apt upgrade
#       - name: step-02
#         run : sudo apt install git curl
#       - name: download & install pandoc
#         run : sudo curl -L https://github.com/jgm/pandoc/releases/download/2.14.0.3/pandoc-2.14.0.3-1-amd64.deb > pandoc.deb && sudo dpkg -i pandoc.deb
#       - name: download & install jq
#         run : sudo curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 > jq && sudo cp jq /usr/bin/jq && sudo chmod +x /usr/bin/jq
#       - name: where is my repo?
#         run : ls -lah
#       - name: build it!
#         run : bash ssg.sh
#       - name: ls it
#         run : ls -lah out
#       - name: clone the website
#         run : cd .. && git clone https://github.com/fuadnafiz98/notes.git && cd notes
#       - name: move files 
#         run : mv ../bash-pandoc-ssg/out/* . && ls -lah 
#       - name: push it?
#         run : git add . && git commit -m "new site deployed" && git remote add origin https://github.com/fuadnafiz98/notes.git && git push origin master

